### ISSUE TITLE
The app isn't pulling user info when the user is having a profile pic set on servers other than official Flarum one

### ISSUE THREAD

**Issue by EnzoBeth** [RomanticD/Flarum-iOS-App-UnofficialDemo#1]
The app don't pull user info when connected to another server

Here my console logs

 current api url: https://champollion-ensemble.tech/api/discussions
current page: 1
has next page: false
has prev page: false
2023-09-05 23:28:04.983025+0200 FlarumiOSApp[33706:1223294] [AXRuntimeCommon] Unknown client: FlarumiOSApp
Fetching User Info : id 1 at: https://champollion-ensemble.tech/api/users/1
Fetching User Info : id 1 at: https://champollion-ensemble.tech/api/users/1

**Comment by RomanticD** [comment]
Please download the latest code, and it should work fine. The root cause was that your Flarum installation didn't have the 'bestAnswer' feature enabled (I initially assumed it was enabled by default). I've made modifications to the relevant code in the repository to make it optional, which has resolved the issue.
